FROM node:20

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available) into the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Set environment variables
ENV PORT=5000

# Expose the port the app will run on
EXPOSE 5000

# Command to run the application
CMD [ "node", "index.js" ]
